services:
  surrealdb:
    image: surrealdb/surrealdb:v1.5.5
    entrypoint:
      - /surreal
      - start
      - --auth
      - --user
      - root
      - --pass
      - root
      - rocksdb://mydata/data.db
    volumes:
      - db-data:/mydata/data.db

  mqtt:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  tenant-api:
    image: cosmtrek/air
    ports:
      - 8080:8080
    environment:
      DB_HOST: surrealdb
    working_dir: /go/src/github.com/findursmile/tenant-api
    volumes:
      - ../tenant:/go/src/github.com/findursmile/tenant-api
    depends_on:
      surrealdb:
        condition: service_started
      mqtt:
        condition: service_started

  tenant-dashboard:
    image: node:22-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ../tenant-dashboard:/app

  processor:
    image: ghcr.io/findursmile/processor
    volumes:
      - ../processor:/app
    restart: on-failure
    depends_on:
      surrealdb:
        condition: service_started
      mqtt:
        condition: service_started

  user-api:
    image: ghcr.io/findursmile/user-api
    ports:
      - 8989:8000
    volumes:
      - ../processor:/app
    depends_on:
      surrealdb:
        condition: service_started
      mqtt:
        condition: service_started

  user-dashboard:
    image: node:22-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 5174:5173
    working_dir: /app
    volumes:
      - ../user:/app

volumes:
  db-data:
